language: php

install:
  - travis_retry composer install --no-interaction --prefer-source

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

notifications:
  email: false
