language: php

install:
  - travis_retry composer install --no-interaction --prefer-source

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email: false
